[package]
name = "myarchinstall"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono-tz = "0.10.0"
dotenv = "0.15.0"
serde = { version = "1.0.214", features = [ "derive" ] }
serde_json = "1.0.132"
toml = "0.8.19"
