# Configurações de timezone
[timezone]
region = "America"
city = "Sao_Paulo"

# Setting up the location
[location]
language = ["en_US.UTF-8 UTF-8"]
keymap = "br-abnt2"

# Configurações gerais do sistema
[system]
hostname = "arch"
root_password = "arch"
username = "arch"
user_password = "arch"

[packages]
essentials = [
  "dosfstools",
  "os-prober",
  "mtools",
  "network-manager-applet",
  "networkmanager",
  "wpa_supplicant",
  "wireless_tools",
  "dialog",
  "sudo",
]
