name: myarchinstall_tests

on:
  push:
    branches: [ "tests", "debug" ]
  pull_request:
    branches: [ "tests", "debug" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
